apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.name }}-cron"
  namespace: edge
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 8
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: cron-sa
          restartPolicy: Never
          containers:
            - name: "{{ .Values.name }}-cron"
              image: quay.io/rh_ee_cschmitz/ose-cli-edge:latest
              env:
              - name: DEPLOYMENT_NAME
                value: "{{ .Values.name }}-yolo"
              command:
                - /start.sh
