apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.name }}-cron"
  namespace: edge
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 8
      activeDeadlineSeconds: 600
      template:
        metadata:
          annotations:
            alpha.image.policy.openshift.io/resolve-names: '*'
        spec:
          serviceAccountName: cron-sa
          restartPolicy: Never
          containers:
            - name: "{{ .Values.name }}-cron"
              image: ose-cli-edge:latest
              imagePullPolicy: IfNotPresent
              env:
              - name: DEPLOYMENT_NAME
                value: "{{ .Values.name }}-yolo"
              command:
                - /start.sh
