kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: "{{ .Values.name }}-yolo"
  namespace: edge
  labels:
    type: yolo
    current_yolo_version: v1
    app: "{{ .Values.name }}-yolo"
    app.kubernetes.io/component: "{{ .Values.name }}-yolo"
    app.kubernetes.io/instance: "{{ .Values.name }}-yolo"
    app.kubernetes.io/name: "{{ .Values.name }}-yolo"
    app.openshift.io/runtime-namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.name }}-yolo"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}-yolo"
        deployment: "{{ .Values.name }}-yolo"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  type: yolo
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: "yolo"
          image: yolo:v1
          env:
            - name: SOURCE_NAME
              value: "{{ .Values.name }}"
            - name: SOURCE_SERVER
              value: "rtsp://mediamtx:8554"
            - name: SINK_SERVER
              value: "rtsp://mediamtx:8554"
            - name: SINK_NAME
              value: "{{ .Values.name }}-yolo"
          resources:
            limits:
              cpu: "{{ .Values.limit_cpu }}"
            requests:
              cpu: "{{ .Values.request_cpu }}"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
